docs(trace): described usage if interface and href more clearly
catenax-ng/eclipse-tractusx.github.io pull request #12
Opened 2023-06-26 12:59 UTC by markuskeidl

After some Catena-X internal discussions, we now can describe more clearly how submodel endpoints w.r.t. interface and href should be used. This pull requests documents this.

2023-06-26 14:22 UTC, arnoweiss commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
>          "subprotocol": "IDS",
when referring to CX-0002 R3.2, this should be DSP.

2023-06-27 06:54 UTC, markuskeidl commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
>          "subprotocol": "IDS",
Ok. There are several other references to IDS, now DPS. I will update the pull request accordingly.

2023-06-27 07:21 UTC, arnoweiss commented
looks good to me.

2023-06-29 09:38 UTC, mhellmeier requested changes
@markuskeidl : Can you please update the branch by merging or rebasing the current status of the `docs/trace-release-3.2` into this one?

Further, please update the changelog accordingly.

2023-06-30 11:19 UTC, markuskeidl commented
> @markuskeidl : Can you please update the branch by merging or rebasing the current status of the `docs/trace-release-3.2` into this one?
> 
> Further, please update the changelog accordingly.

Done.

2023-06-30 14:19 UTC, mhellmeier approved these changes
LGTM

2023-06-30 14:19 UTC, merged