docs(trace): setting the visibility of entries in a digital twin's specificAssetId is now mandatory to ensure need-know
catenax-ng/eclipse-tractusx.github.io pull request #15
Opened 2023-07-12 12:04 UTC by markuskeidl

2023-07-18 08:41 UTC, markuskeidl commented
@mhellmeier You said that two reviewers are required normally. Who should or can I add as second reviewer? @matgnt ?

2023-07-18 09:44 UTC, matgnt commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +To enforce a strict need-to-know   (and prevent data from being exposed to non-authorized parties), the visibility of entries in the attribute `specificAssetId` must be protected, i.e.,their visibili
in case 'manufacturer' is equal to the creator of the twin, I think it doesn't need to be allow-listed via the externalSubjectId separately. Creator of an entry has access by default.

2023-07-18 09:44 UTC, matgnt commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +To enforce a strict need-to-know   (and prevent data from being exposed to non-authorized parties), the visibility of entries in the attribute `specificAssetId` must be protected, i.e.,their visibili
ah, a bit later, this is explained.... therefore I wonder why the manufcaturer is mentioned here. typically the manufacturer is also the creator / owner of the twin, right?

2023-07-18 09:44 UTC, matgnt commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +  - `{path}`: This part is forwarded to the backend data service by the EDC data plane. Together with the EDC asset information (see below) it must contain all information for the backend data servic
'EDC asset information' is not really forwarded I would say. only the contract agreement id and now, also the BPN, but I think no asset information as far as I could tell.

2023-07-18 09:44 UTC, matgnt commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +According to CX-0002, the backend data service identified via `href`and the filter criteria in `subprotocolBody` MUST be conformant to the Asset Administration Shell Profile SSP-003 of the Submodel S
Can we additionally explain something like "the consumer needs to append /$value to the href endpoint"

2023-07-18 12:21 UTC, mhellmeier requested changes

2023-07-18 12:21 UTC, mhellmeier commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +To enforce a strict need-to-know   (and prevent data from being exposed to non-authorized parties), the visibility of entries in the attribute `specificAssetId` must be protected, i.e.,their visibili
Remember and check again some spelling things. For example, a space is missing after the comma here: "protected, i.e.,their visibility"

2023-07-18 12:21 UTC, mhellmeier commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +  - `{path}`: This part is forwarded to the backend data service by the EDC data plane. Together with the EDC asset information (see below) it must contain all information for the backend data servic
Also, what does "This part" right at the beginning mean? Does it refer to `{path}` only or the whole `href`?

2023-07-19 08:04 UTC, markuskeidl commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +To enforce a strict need-to-know   (and prevent data from being exposed to non-authorized parties), the visibility of entries in the attribute `specificAssetId` must be protected, i.e.,their visibili
The manufacturer should be the creator, correct. But I still think the sentence here is correct. Assume a situation where the creator is not the manufacturer (not sure if that makes sense at all), but in this case I think the manufacturer should still have access to the DT (and is allowed to). In this situation, the manufacturer must actually be added via externaSubjectId.

2023-07-19 08:07 UTC, markuskeidl commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +  - `{path}`: This part is forwarded to the backend data service by the EDC data plane. Together with the EDC asset information (see below) it must contain all information for the backend data servic
@matgnt I do not mean that the EDC asset information is forwarded. What I mean is that on a conceptual level, asset information + {path} must have all information to resolve the correct submodel.

@mhellmeier This part refers to {path}, yes. Would "This string" work better?

2023-07-19 08:08 UTC, markuskeidl commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +According to CX-0002, the backend data service identified via `href`and the filter criteria in `subprotocolBody` MUST be conformant to the Asset Administration Shell Profile SSP-003 of the Submodel S
This part was no updated in another pull request. Also, that the data consumer must do this is described in section "Data Consumption with AAS Submodel Descriptor Endpoints" later.

2023-07-19 08:09 UTC, markuskeidl commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +To enforce a strict need-to-know   (and prevent data from being exposed to non-authorized parties), the visibility of entries in the attribute `specificAssetId` must be protected, i.e.,their visibili
Added linting now to my pre-commit check. So, will fix this with the next update once you agreed to my above comments :)

2023-07-19 09:11 UTC, mhellmeier commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +  - `{path}`: This part is forwarded to the backend data service by the EDC data plane. Together with the EDC asset information (see below) it must contain all information for the backend data servic
Yes, or "The `{path}` string"

2023-07-19 09:37 UTC, mhellmeier commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +  - `{path}`: This part is forwarded to the backend data service by the EDC data plane. Together with the EDC asset information (see below) it must contain all information for the backend data servic
The commit is missing, @markuskeidl.

2023-07-19 09:38 UTC, mhellmeier requested changes
Can you please push the missing commit, as discussed in the conversion?

Further, please merge the current status of `docs/trace-release-3.2` into this branch and solve the merge conflicts.

2023-07-19 09:45 UTC, markuskeidl commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +  - `{path}`: This part is forwarded to the backend data service by the EDC data plane. Together with the EDC asset information (see below) it must contain all information for the backend data servic
Yeah, was in a meeting in parallel. I will commit in a few minutes. Regarding the "EDC asset information" - @matgnt If you still think we should change that, can you create a pull request for it? It's not related to this issue (visibility), so I don't want to stop because of this. We need to update the KIT and then the standards until Friday.

2023-07-19 09:46 UTC, markuskeidl commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +  - `{path}`: This part is forwarded to the backend data service by the EDC data plane. Together with the EDC asset information (see below) it must contain all information for the backend data servic
Done

2023-07-19 09:54 UTC, markuskeidl commented
Merge conflicts are now resolved.

2023-07-19 09:56 UTC, markuskeidl commented
Please do not yet merge the PR as I need to verify the syntax for externalSubjectId first. It might have been changed.

2023-07-19 10:28 UTC, matgnt commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +To enforce a strict need-to-know   (and prevent data from being exposed to non-authorized parties), the visibility of entries in the attribute `specificAssetId` must be protected, i.e.,their visibili
how about:
```
visibility must be restricted to only the customers of the part and in case the creator is not the manufacturer, also to the manufacturer. For that, the attribute `externalSubjectId` must be used.
```

2023-07-20 09:00 UTC, matgnt approved these changes

2023-07-20 09:53 UTC, merged