Docs/aspect models updates 3.2
catenax-ng/eclipse-tractusx.github.io pull request #18
Opened 2023-07-18 08:04 UTC by jacewski-bosch

This PR updates all Aspect Models for CX Release 3.2
Links to new and updated standardization dDocuments are still a todo (not available yet)

2023-07-18 09:35 UTC, mhellmeier requested changes
The merge conflicts should be solved.

2023-07-19 07:25 UTC, jacewski-bosch commented
@mhellmeier fixed merge conflicts and thus the other issue as well

2023-07-19 07:42 UTC, mhellmeier requested changes
Great, @jacewski-bosch ! Could you please update the Changelog and add one or two sentences to describe the changes (like renaming from `SerialPartTypization` to `SerialPart` etc.)?

Changelog file: https://github.com/catenax-ng/eclipse-tractusx.github.io/blob/docs/trace-release-3.2/docs/kits/Traceability%20Kit/page_changelog.md

2023-07-19 07:42 UTC, mhellmeier commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +#### Submodel TractionBatteryCode
If you look into this markdown file, `TractionBatteryCode` can be found two times. Could you please remove one of the duplicates?

2023-07-19 09:09 UTC, jacewski-bosch commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +#### Submodel TractionBatteryCode
removed

2023-07-19 09:11 UTC, jacewski-bosch commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +###### Option 1: Same EDC Asset Structure as in Release 3.1
@mhellmeier please check if this header has the correct level

2023-07-19 09:11 UTC, jacewski-bosch commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +###### Option 2: EDC Asset Structure on Catalog Part Level
@mhellmeier please check if this header has the correct level

2023-07-19 09:11 UTC, jacewski-bosch commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +###### Data Consumption with AAS Submodel Descriptor Endpoints
@mhellmeier please check if this header has the correct level

2023-07-19 09:34 UTC, mhellmeier commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +###### Option 1: Same EDC Asset Structure as in Release 3.1
Header level is correct!

2023-07-19 09:34 UTC, mhellmeier commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +###### Option 2: EDC Asset Structure on Catalog Part Level
Header level is correct!

2023-07-19 09:34 UTC, mhellmeier commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +###### Data Consumption with AAS Submodel Descriptor Endpoints
Header level is correct!

2023-07-19 09:34 UTC, mhellmeier approved these changes
LGTM

2023-07-19 09:35 UTC, merged