docs(trace): added assumptions and non-functional requirements to architecture
catenax-ng/eclipse-tractusx.github.io pull request #26
Opened 2023-10-13 12:58 UTC by markuskeidl

2023-10-13 13:44 UTC, mhellmeier requested changes

2023-10-13 13:44 UTC, mhellmeier commented on docs-kits/kits/Traceability Kit/page_architecture-view.md
> +In general, data must be provided to the Catena-X network using the Data Space Protocol (DSP). As standard for digital twins the Asset Administration Shell (AAS) standard is used - this is relevant f
Maybe we should link the Data Space Protocol (DSP) here?

2023-10-16 06:02 UTC, markuskeidl commented on docs-kits/kits/Traceability Kit/page_architecture-view.md
> +In general, data must be provided to the Catena-X network using the Data Space Protocol (DSP). As standard for digital twins the Asset Administration Shell (AAS) standard is used - this is relevant f
I have no official link to this protocol. We also don't have a link to the AAS standard - probably in other places as well. I might make most sense to either add this to any reference of DSP or AAS or ... or to add a reference section somewhere.

2023-10-16 07:31 UTC, mhellmeier approved these changes
LGTM

2023-10-16 07:58 UTC, matgnt approved these changes

2023-10-16 07:58 UTC, matgnt commented on docs-kits/kits/Traceability Kit/page_architecture-view.md
> +In general, data must be provided to the Catena-X network using the Data Space Protocol (DSP). As standard for digital twins the Asset Administration Shell (AAS) standard is used - this is relevant f
DSP Link would be: https://docs.internationaldataspaces.org/dataspace-protocol/

2023-10-16 07:58 UTC, matgnt commented on docs-kits/kits/Traceability Kit/page_architecture-view.md
> +In general, data must be provided to the Catena-X network using the Data Space Protocol (DSP). As standard for digital twins the Asset Administration Shell (AAS) standard is used - this is relevant f
should we reference SAMM as well?

2023-10-16 08:10 UTC, merged