docs(ic): updated business view for Industry Core
catenax-ng/eclipse-tractusx.github.io pull request #45
Opened 2024-01-09 08:58 UTC by markuskeidl

2024-01-11 16:05 UTC, mhellmeier requested changes
There needs to be a `.license` file for every image added to the KITs. See [TRG 7.08](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-08#self-created-images) for more information.

When also using our standard CC-BY-4.0 license, this would lead to put the image itself with all its content open source. Since there are external icons and company logos involved (like on the `DataChain_World.png`) I don't think this would be okay.

2024-01-12 08:29 UTC, DrDanielMetz commented on docs-kits/kits/Industry Core Kit/page_business_view.mdx
> + The Industry Core enables a data sovereign data exchange based on parts and vehicles and lays the foundation for compliance with supply chain regulations.
data sovereign data exchange => sovereign data exchange

2024-01-12 08:29 UTC, DrDanielMetz commented on docs-kits/kits/Industry Core Kit/page_business_view.mdx
> +The Industry Core describes a component at type and/or instance level, makes it identifiable and discoverable in the network and enables traversing across several levels.
describes a component => describes a physical part, component or material

Just to align with the wording above and to know what is meant with component.

2024-01-12 08:29 UTC, DrDanielMetz commented on docs-kits/kits/Industry Core Kit/page_business_view.mdx
> +Parts and vehicles at type level can be provided at the earliest when the part has been assigned to a supplier. The linking of subcomponents at this point in time is often referred to as BoM as plann
Parts and vehicles at type level can be provided at the earliest when the part has been assigned to a supplier.

I do not understand this sentence. Why is it not possible to publish a part at type level once I have designed it and I am ready to produce and ship it to my clients?

Proposal:
Parts and vehicles at type level can be provided at the earliest when the part has been designed and is available for ordering as a catalog part.

2024-01-12 08:29 UTC, DrDanielMetz commented on docs-kits/kits/Industry Core Kit/page_business_view.mdx
> +The Industry Core enables a data sovereign data exchange based on parts and vehicles and the realization of n-tier data chains.
data sovereign data exchange => sovereign data exchange

2024-01-12 08:29 UTC, DrDanielMetz commented on docs-kits/kits/Industry Core Kit/page_business_view.mdx
> +By reusing the core- & enablement services and the uniform usage of digital twins
By reusing => The reusing ... accelerates

2024-01-12 08:29 UTC, DrDanielMetz commented on docs-kits/kits/Industry Core Kit/page_business_view.mdx
> +To do so, once is enough: Once EDC, BPN, and Decentralized Registry + digital twins according to standardized semantics are established, numerous use cases can be enabled by extending the tech-stack
Change the symbol + => and

2024-01-12 16:28 UTC, mhellmeier approved these changes

2024-01-12 16:30 UTC, merged