Initial changes for Upstream Visibility
catenax-ng/eclipse-tractusx.github.io pull request #53
Opened 2024-02-12 16:14 UTC by eckardg

I added the aspect models singleLevelUsageAsBuilt and singleLevelUsageAsPlanned with descriptions, enhanced the UniqueIdPush Notification part and the changelog.
The aspect models still have to be updated to the final version to be published in the standard, with links and examples. The corresponding openAPI specification also still has to be added.

2024-02-13 08:24 UTC, mhellmeier approved these changes
LGTM, but should be merged together with #54

2024-02-15 13:06 UTC, arnoweiss commented
My issue with this is the lack of API specification here. Previous discussions showed that the introduction of this aspect model requires a different provisioning mechanism than for the other aspects. Data Model & API are interlinked tightly, so they should be in the same PR.

2024-02-15 13:09 UTC, arnoweiss requested changes
Add API spec by either
- defining detailed mechanism to extend uuid push (supplier-side)
- defining detailed mechanism extending POST {{aasId}}/submodel-descriptors (supplier-side)
- defining detailed mechanism provisioning via GET /submodel (customer-side)

2024-02-15 15:28 UTC, eckardg commented
@arnoweiss : You are perfectly right. API specification still to be added, we are waiting for the final aspect model

2024-02-20 16:49 UTC, eckardg commented
> My issue with this is the lack of API specification here. Previous discussions showed that the introduction of this aspect model requires a different provisioning mechanism than for the other aspects. Data Model & API are interlinked tightly, so they should be in the same PR.

Yes, I will do this in the next version. Details are not yet available

2024-02-20 16:50 UTC, eckardg commented
> Add API spec by either
> 
> * defining detailed mechanism to extend uuid push (supplier-side)
> * defining detailed mechanism extending POST {{aasId}}/submodel-descriptors (supplier-side)
> * defining detailed mechanism provisioning via GET /submodel (customer-side)

This will come with the next update, details are not yet available (have to be put in the standard first)

2024-02-27 18:30 UTC, arnoweiss approved these changes
Two minor suggestions, no blockers. Thanks for the extensive explanations - that's exactly what kits are for.

2024-02-27 18:30 UTC, arnoweiss commented on docs-kits/kits/Industry Core Kit/Software Development View/part_uniqueidpush.mdx
> -- The asset ID  must be "uniqueidpushnnotification-receipt".
specifying what `@id` must be set makes it physically impossible to deploy multiple EDC assets of for this API. This may come back to haunt you when a major version-increment forces providers to operate the new and and old API. I think for selecting the right asset in the catalog the dct:type and cx-common:version property should be used. So I'd argue to ditch this line entirely.

2024-02-29 08:08 UTC, mhellmeier commented on docs-kits/kits/Industry Core Kit/Software Development View/part_uniqueidpush.mdx
> -- The asset ID  must be "uniqueidpushnnotification-receipt".
This will be adjusted by @markuskeidl

2024-02-29 08:08 UTC, merged