docs(trace): Update specificAssetIds with intrinsicId as a techical l…
catenax-ng/eclipse-tractusx.github.io pull request #57
Opened 2024-02-16 15:45 UTC by nirschlk

With the introduction of a look-up key in the specificAssetIDswe ensure a standardised identification of a digital twin and
correct semantic filling of specificAssetIDs 

Introduction the new attribute "intrinsicId" in the specific AssetIs.

2024-02-16 17:23 UTC, arnoweiss requested changes
1. For whom is this mandatory?
2. What's the intended behavior concerning visibility? Should it be possible to set it publicly readable?

2024-02-20 12:04 UTC, nirschlk commented
My answers to the raised questions:
1. If I interpret the question correctly, this is mandatory for the data providers similar to the previous filling of the PartInstanceID.
2. In terms of visibility, this should be the same as for the PartInstanceID and, as far as I know, there was no restriction for this. The new attribute should be used instead of the PartInstanceID to access the digital twin.

2024-02-20 12:23 UTC, arnoweiss commented
If `intrinsicId` and `partInstanceId` are synonymous, we should remove the latter entirely, I think. We don't have backward compatibility requirements for R24-5.

2024-02-21 07:13 UTC, markuskeidl commented on docs-kits/kits/Industry Core Kit/Software Development View/page_digital-twins.mdx
> +    - Currently though, no matter if you want to lookup serialized parts or batches, you can use intrinsicId (using the serial number or the batch number as search parameter value).
This is true, but I would re-write it more to cleary describe that currently the intrinsicId should be used for searching. That's why it was added. That you can also use partInstanceId, batchId, ... is also valid if you want to (optionally).  Right now, e.g., only batches are mentioned regarding this. This whole bullet point needs a better re-write.

2024-02-21 10:31 UTC, arnoweiss commented on docs-kits/kits/Industry Core Kit/Software Development View/page_digital-twins.mdx
> +| intrinsicId    | Mandatory    | The serial number of the part from the manufacturer.                                         | String |
That means that intrinsicId duplicates the content of either partInstanceId or batchId so that there's a common search-key?

2024-03-04 12:51 UTC, markuskeidl commented on docs-kits/kits/Industry Core Kit/Software Development View/page_digital-twins.mdx
> +| intrinsicId    | Mandatory    | The serial number of the part from the manufacturer.                                         | String |
Yes

2024-03-06 20:14 UTC, nirschlk commented on docs-kits/kits/Industry Core Kit/Software Development View/page_digital-twins.mdx
> +| partInstanceId | Optional     | The serial number of the part from the manufacturer.                                         | String |
ok; Worked on the Commit: docs(trace): Work on review results for intrinsicId

2024-03-06 20:14 UTC, nirschlk commented on docs-kits/kits/Industry Core Kit/Software Development View/page_digital-twins.mdx
> +| intrinsicId    | Mandatory    | The serial number of the part from the manufacturer.                                         | String |
ok; Worked on the Commit: docs(trace): Work on review results for intrinsicId

2024-03-06 20:14 UTC, nirschlk commented on docs-kits/kits/Industry Core Kit/Software Development View/page_digital-twins.mdx
> +| intrinsicId    | Mandatory    | Also the number of the batch from the manufacturer.<br/><br/>Currently, we also use the batch number as intrinsicId. This makes looking up digital twins for serializ
ok; Worked on the Commit: docs(trace): Work on review results for intrinsicId

2024-03-06 20:15 UTC, nirschlk commented on docs-kits/kits/Industry Core Kit/Software Development View/page_digital-twins.mdx
> +    - Currently though, no matter if you want to lookup serialized parts or batches, you can use intrinsicId (using the serial number or the batch number as search parameter value).
ok; Worked on the Commit: docs(trace): Work on review results for intrinsicId

2024-03-06 20:16 UTC, nirschlk commented
I have adapted the documentation again based on the review comments. I have expanded the descriptions of intrinsicID and added the respective characteristics of digital twins.

2024-03-28 07:35 UTC, arnoweiss approved these changes

2024-03-28 10:48 UTC, merged