Update the Traceability KIT because of the EDC asset structure rework for Release 3.2
catenax-ng/eclipse-tractusx.github.io pull request #6
Opened 2023-05-26 07:11 UTC by markuskeidl

With release 3.2 of Catena-X, the - previously fixed - structure for EDC assets for submodels of digital twins is changed to give a data provider more freedom in how to model their EDC structure for digital twins. 

As a prerequisite, the format for submodel endpoints in the DTR is changed to allow this change. 

Also, the endpoint format is changing because of the switch to the AAS v3.0 standard. This is also integrated in this request.

2023-05-26 08:02 UTC, mhellmeier requested changes
The current PR wants to merge the changes from `docs/edc-asset-structure-rework` into `main`. For release 3.2, we want to collect all Traceability KIT changes in `docs/trace-release-3.2`. So please change the target branch from `main` to `docs/trace-release-3.2`.
https://github.com/catenax-ng/eclipse-tractusx.github.io/tree/docs/trace-release-3.2

2023-05-26 09:17 UTC, markuskeidl commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +The actual access information for the EDC is part of the endpoint attribute in the submodel descriptor.
Linting errors are fixed now

2023-05-31 08:08 UTC, mhellmeier approved these changes
LGTM

2023-05-31 08:08 UTC, merged

2023-05-31 14:20 UTC, BirgitBoss reviewed
see updated CX-0002 guideline for agreed SubmodelDescriptor in AAS Digital Twin Registry

2023-05-31 14:20 UTC, BirgitBoss commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +        "subprotocol": "IDS/AAS",
must be "subprotocol" : "IDS"

2023-05-31 14:20 UTC, BirgitBoss commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +```json
The complete SubmodelDescriptor Example in CX-0002 now looks like this:

````json
{

    “id": “<unique ID of submodel>",

    "semanticId": {“type”: “ExternalReference”, “keys”: [{“type”: “GlobalReference”, “value”: “urn:bamm:io.catenax.material_for_recycling:1.1.0#MaterialForRecycling”]},

   "endpoints": [ 

     {

    "protocolInformation": {

        “href": ”https://edc.data.plane/<path>/submodel",

        "endpointProtocol": "HTTP",

        "endpointProtocolVersion: ["1.1"],

        "subprotocol": "IDS",

        "subprotocolBody": "asset:prop:id=123; idsEndpoint=http://edc.control.plane/", 

        "subprotocolBodyEncoding": "plain",

        "securityAttributes": "securityAttributes": [ { "type": "NONE", "key": "NONE", "value": "NONE"  ]

    }

    "interface": "SUBMODEL-3.0",

  }

 ]

}

````

2023-05-31 14:20 UTC, BirgitBoss commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +- `interface` must be set to "https://admin-shell.io/aas/API/3/0/SubmodelServiceSpecification/SSP-003"
SUBMODEL-3.0

2023-05-31 14:20 UTC, BirgitBoss commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +  - `/shells/{aasIdentifier}/submodels/{submodelIdentifier}/submodel/$value`: A valid API call according to the AAS Submodel Service Specification with {aasIdentifier} the id of the digital twin and
the path parameter value (mit dem Dollarzeichen davor) is NOT part of the endpoint. This is something the data consumer needs to add (it is called a path parameter, path parameter start with $). Also other query parameters might be added by the data consumer

2023-05-31 14:20 UTC, BirgitBoss commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +  - `/submodel`: This is currently the only API method that must be supported for Traceability
wahrscheinlich nicht oder, das entspricht Content=Normal. Das hatten wir bislang noch nicht unterstützt. Das ist erst für R3.3. von CX geplant.

2023-05-31 14:20 UTC, BirgitBoss commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +  - `/$value`: For release 3.2, data providers only need to support "value" as serialization modifier.
Das war schon immer so. NEU: ab sofort ist value nicht mehr Teil des Endpunkts, sondern muss explizit vom data consumer ergänzt werden (siehe CX-0002)

2023-05-31 14:20 UTC, BirgitBoss commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +- `subprotocol` must be set to "IDS/AAS"
must be "IDS"

2023-05-31 14:20 UTC, BirgitBoss commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +  - `asset:prop:id=123`: A criteria used for filtering the EDC catalog which must only return exactly one EDC asset - this must be ensured by the data provider when registering its data in the EDC. A
wohl ein blank zu viel vor dem - ?

typo: form ==> from ?

2023-05-31 14:20 UTC, BirgitBoss commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +- Option 1: Digital twins, i.e., their submodels, are registered in the EDC the same way as for release 3.1, i.e., one EDC asset is created for every submodel of a digital twin. In the example above,
a string concatenating from AAS ID and Submodel ID - this is not clear from the example alone

2023-05-31 14:20 UTC, BirgitBoss commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +    "semanticId": {
see complete example of semanticId in CX-0002 example. This is not correct any longer for AAS 3.0

    "semanticId": {“type”: “ExternalReference”, “keys”: [{“type”: “GlobalReference”, “value”: “urn:bamm:io.catenax.material_for_recycling:1.1.0#MaterialForRecycling”]},

2023-05-31 14:20 UTC, BirgitBoss commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +        "interface": "https://admin-shell.io/aas/API/3/0/SubmodelServiceSpecification/SSP-003",
SUBMODEL-3.0

2023-05-31 14:20 UTC, BirgitBoss commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +          "href": "https://data-plane.edc.catena-x.net/shells/urn:uuid%3A75e98d67-e09e-4388-b2f6-ea0a0a642bfe/submodels/urn%3Auuid%3A34b73238-4dc2-424a-985d-4afa01d7203e/submodel/$value",
1) This link is not correct for Asset Administration Shell Repositories: it would be https://data-plane.edc.catena-x.net/shells/urn:uuid%3A75e98d67-e09e-4388-b2f6-ea0a0a642bfe/submodels/urn%3Auuid%3A34b73238-4dc2-424a-985d-4afa01d7203e/$value
2) §value ist not part of the endpoint, so only https://data-plane.edc.catena-x.net/shells/urn:uuid%3A75e98d67-e09e-4388-b2f6-ea0a0a642bfe/submodels/urn%3Auuid%3A34b73238-4dc2-424a-985d-4afa01d7203e

if the data consumer is not using an AAS Repository or a Submodel Repository then it is
https://data-plane.edc.catena-x.net/anything/submodel

2023-05-31 14:20 UTC, BirgitBoss commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +          "subprotocol": "IDS/AAS",
only "IDS"

2023-05-31 14:20 UTC, BirgitBoss commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +- A data consumer must first identify the protocol that must be used to retrieve the submodel data based on the `subprotocol`. For data transfer with Catena-X EDCs, this is "IDS/AAS"
"IDS"

2023-05-31 14:20 UTC, BirgitBoss commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +- Finally, using the id from the contract agreement with the control plane, the data consumer initiates the data transfer with the EDC data plane of the data provider referenced in the `href`. In thi
grammar

2023-05-31 14:20 UTC, BirgitBoss commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +The endpoint `href` in the submodel descriptor cannot be used directly to contact an EDC and access the data in Catena-X.
1st step is: add path and query parameters as needed. So far it is only mandatory for Digital Twin Solution Provider to implement /submodel/$value but not /submodel

2023-05-31 14:31 UTC, mhellmeier commented
@markuskeidl: Can you please integrate the suggested edits from @BirgitBoss in a new branch? Also, an update to the changelog would be helpful.