docs(trace): updated Unique ID Push Open API specification to include upstream visibility (connect-to-child)
catenax-ng/eclipse-tractusx.github.io pull request #61
Opened 2024-02-22 08:41 UTC by markuskeidl

This PR is based on https://github.com/catenax-ng/eclipse-tractusx.github.io/pull/60 and requires a merge of this PR first.

There are still two open issues regarding this change:

- Should the extension of the Unique ID Push API with upstream visibility be integrated into IC which means that the Open API specification in IC must be updated. Or should we add this update as a separate Open API specification only in the Traceabilty KIT. 
- Should there be two EDC assets, one for each method (connect-to-parent, connect-to-child), or should be there be only one EDC asset through which both API calls are routed?

Depending on the answer to the above two questions, different parts of the IC and Trace KIT must be updated.

2024-02-22 08:50 UTC, nirschlk reviewed
looks define to me.

2024-02-22 10:17 UTC, eckardg commented
@markuskeidl : I recommend to have two assets and two API specifications.
- two assets: connect-to-parent will be called by the supplier, connect-to-child will be called by the customer; it can be necessary to add different policies
- two API specifications: this makes it easier to refer to the specifications in different KITs and standards

2024-02-22 16:14 UTC, arnoweiss commented
Sounds to me like it should be two separate EDC-assets. If it's one and both endpoints are optional, there's no way for a Consumer to know what the API behind the asset will actually satisfy. If it's two, this will be visible in the catalog already.

2024-02-23 12:41 UTC, eckardg commented
looks fine for me. The body of the connect-to-child still has to be updated to correspond to the aspect model. I assume we will do this later?

2024-02-27 18:18 UTC, arnoweiss approved these changes
Thanks for preparing this - it's fine overall. I'd appreciate help understand the parsing logic on the `listOfItems` property

2024-02-27 18:18 UTC, arnoweiss commented on openApi/traceability/unique-id-push-trace-extension.yaml
> +            oneOf:
How will a receiver of this message know what of the three options to parse each payload into?

2024-03-01 17:24 UTC, nirschlk approved these changes
fine for me.

2024-03-01 20:06 UTC, DrDanielMetz commented on openApi/traceability/unique-id-push-trace-extension.yaml
> +          type: string
urn_samm_io.catenax.shared.business_partner_number_2.0.0_BpnlTrait

could be used.

2024-03-01 20:06 UTC, DrDanielMetz commented on openApi/traceability/unique-id-push-trace-extension.yaml
> +        catenaXId:
urn_samm_io.catenax.shared.uuid_2.0.0_UuidV4Trait

could be used

2024-03-06 09:53 UTC, markuskeidl commented on openApi/traceability/unique-id-push-trace-extension.yaml
> +            oneOf:
With three options you mean serial part, batch or JIS part? You can see which type of part it is (in the list) using the local IDs. For serialized part, it's partInstanceId, for batches it's batchID and so on.

2024-03-06 09:54 UTC, markuskeidl commented on openApi/traceability/unique-id-push-trace-extension.yaml
> +          type: string
I already updated that locally. The next version of the PR will use this type.

2024-03-06 09:54 UTC, markuskeidl commented on openApi/traceability/unique-id-push-trace-extension.yaml
> +        catenaXId:
I already updated that locally. The next version of the PR will use this type.

2024-03-06 12:49 UTC, DrDanielMetz requested changes

2024-03-07 08:18 UTC, markuskeidl commented on openApi/industrycore/unique-id-push_2-1-0.yaml
> +      description: Defining a string value for the context
I don't want to do that. The schema for ContextCharacteristic is from the message header standard aspect model. I do not want to change this definition, ideally, if possible, I would only reference this schema externally anyway.

2024-03-07 08:41 UTC, DrDanielMetz commented on openApi/industrycore/unique-id-push_2-1-0.yaml
> +      description: Defining a string value for the context
Ok, it is fine for me - personally.

I am just wondering how someone could implement this API correctly if it is unclear which values are possible.
The pattern `<domain>-<subdomain>-<object>:<[major] version>` is not sufficient to answer this as there is also no place where the values for domain, subdomain, and object are described.

So, at the end, you simply need to know it - from somewhere.

With regard to the standard header, it is a general question where such details - which are necessary for a working implementation - are to be defined. I could not answer this question today.

2024-03-07 08:42 UTC, DrDanielMetz approved these changes

2024-03-07 09:56 UTC, merged