Traceability: Remove part_policies and refer to Industry Core
catenax-ng/eclipse-tractusx.github.io pull request #71
Opened 2024-03-21 09:07 UTC by matgnt

Industry Core now describes the policies and we don't need that in Traceability any more.

As discussed, remove the policy section from Traceability Kit, since we now have one in Indistry Core.
I removed the entire file and the imports accordingly, becsause there was no real content left.

2024-03-21 14:09 UTC, mhellmeier requested changes

2024-03-21 14:09 UTC, mhellmeier commented on docs-kits/kits/Traceability Kit/Software Development View/page_data-provider_software-development-view.mdx
> +Access policies like the BPN access policy and Usage Policies / Contract Policies are described in the [policy section of the Industry Core KIT](../../Industry%20Core%20Kit/Software%20Development%20V
I think we should still add information that is only relevant for Traceability, like mentioning the specific Traceability framework agreement ([link to the framework agreement](https://catena-x.net/en/catena-x-introduce-implement/governance-framework-for-data-space-operations), mentioning the specific payload, etc.).

2024-03-22 08:29 UTC, matgnt commented on docs-kits/kits/Traceability Kit/Software Development View/page_data-provider_software-development-view.mdx
> +Access policies like the BPN access policy and Usage Policies / Contract Policies are described in the [policy section of the Industry Core KIT](../../Industry%20Core%20Kit/Software%20Development%20V
right now, all of this is in Core. The link, the 3 possible payloads are the examples for traceability. should I copy them over here as well?

https://github.com/catenax-ng/eclipse-tractusx.github.io/blob/b31d5df2f0b0c52613c2fdeb06950e404f8084e7/docs-kits/kits/Industry%20Core%20Kit/Software%20Development%20View/page_policies.mdx#L64

2024-03-22 09:31 UTC, mhellmeier commented on docs-kits/kits/Traceability Kit/Software Development View/page_data-provider_software-development-view.mdx
> +Access policies like the BPN access policy and Usage Policies / Contract Policies are described in the [policy section of the Industry Core KIT](../../Industry%20Core%20Kit/Software%20Development%20V
Yes, I think it is important to mention the traceability specific payload / operand if people are searching for them.

2024-03-22 10:44 UTC, matgnt commented on docs-kits/kits/Traceability Kit/Software Development View/page_data-provider_software-development-view.mdx
> +Access policies like the BPN access policy and Usage Policies / Contract Policies are described in the [policy section of the Industry Core KIT](../../Industry%20Core%20Kit/Software%20Development%20V
The leftOperands are the ones documented in core. The traceability specific rightOperands are not yet finalized and I'd recommend to only update the here, once they are finalized. They depend on the release of the framework documents and will be documented in the (not yet publicly avialable) cx-odrl-profile repo that is also linked in core.

I'd propose that - for now - I can add the link additionally here, but for now, I would not add the rightOperands to not be forced to update them in too many places. We can think about this, once they are more stable.

2024-03-22 13:52 UTC, mhellmeier commented on docs-kits/kits/Traceability Kit/Software Development View/page_data-provider_software-development-view.mdx
> +Access policies like the BPN access policy and Usage Policies / Contract Policies are described in the [policy section of the Industry Core KIT](../../Industry%20Core%20Kit/Software%20Development%20V
Okay, that's fine for me. Then I will merge this PR. It would be great if you could update the page after the `rightOperand` is finalized.

2024-03-22 13:52 UTC, mhellmeier approved these changes

2024-03-22 13:54 UTC, merged