Docs/trace industry core policies
catenax-ng/eclipse-tractusx.github.io pull request #74
Opened 2024-03-28 14:11 UTC by arnoweiss

remove general sections on policy handling, policies in CX and condense down to the specifics of the IC

2024-03-28 14:25 UTC, matgnt requested changes

2024-03-28 14:25 UTC, matgnt commented on docs-kits/kits/Industry Core Kit/Software Development View/page_policies.mdx
> +As described in the Connector Kit, there is a Credential issued for each Framework Agreement. As the Industry Core (IC)
It's only called 'FrameworkAgreement' in the Credentials. Outside, it is called 'Use Case Framework' to not think about agreements in the sence of a contract - because it is not a contract.
When writting it with a space, I would suggest to not call it Framework Agreement.

2024-03-28 14:25 UTC, matgnt commented on docs-kits/kits/Industry Core Kit/Software Development View/page_policies.mdx
> +    "@context": {
with only cx-policy, but not `https://www.w3.org/ns/odrl.jsonld`
the leftOperand, etc. are not expanded correctly.

```
    "@context": [
        "https://www.w3.org/ns/odrl.jsonld",
        {
            "cx-policy": "https://w3id.org/catenax/policy/"
        }
    ],

```

2024-03-28 14:25 UTC, matgnt commented on docs-kits/kits/Industry Core Kit/Software Development View/page_policies.mdx
> +As the IC in turn relies on a set of other components and concepts, certain Offers in IC-based use-cases will usually
this is certainly not correct. I don't know a use case where we mix the Registry Usage with the Aspects' usage.
there is never a 'and' with e.g. industrycore:1 and digitalTwinRegistry:1
Can you explain a bit more what you had in mind here?

2024-03-28 15:07 UTC, arnoweiss commented on docs-kits/kits/Industry Core Kit/Software Development View/page_policies.mdx
> +As the IC in turn relies on a set of other components and concepts, certain Offers in IC-based use-cases will usually
obviously had a wrong understanding of the mechanism. Pushed an update.

2024-04-02 06:54 UTC, mhellmeier approved these changes

2024-04-02 06:56 UTC, merged