docs(trace): Updated conventions for submodel descriptors and EDC asset structure
catenax-ng/eclipse-tractusx.github.io pull request #9
Opened 2023-06-14 08:59 UTC by markuskeidl

Updated conventions for submodel descriptors and EDC asset structure structure to give data provides more flexibility in how to create EDC assets for submodels of digital twins based on the new AAS v3.0 standard

2023-06-21 06:32 UTC, markuskeidl commented
Merge conflicts fixed - pull request is finished (although there will be changes in the upcoming weeks, I think). But I think it makes sense to add it to the 3.2 KIT to have a somewhat consistent version for implementation @mhellmeier

2023-06-21 10:02 UTC, mhellmeier requested changes

2023-06-21 10:02 UTC, mhellmeier commented on docs/kits/Traceability Kit/page_changelog.md
> +
Thanks for updating the changelog! There are still some other pull requests already merged into the `docs/trace-release-3.2` branch. Would it be possible to mention the already merged changes here? In the future, we should constantly update the changelog in every merge request (missed in the early ones).

2023-06-23 06:50 UTC, markuskeidl commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +        ]
Whitespace issues should be fixed now.

2023-06-23 06:51 UTC, markuskeidl commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +          ]
Whitespace issues should be fixed now.

2023-06-23 06:51 UTC, markuskeidl commented on docs/kits/Traceability Kit/Software Development View/page_software-development-view.md
> +          ]
Whitespace issues should be fixed now.

2023-06-23 06:51 UTC, markuskeidl commented on docs/kits/Traceability Kit/page_changelog.md
> +
Updated changelog with missing messages.

2023-06-23 07:03 UTC, markuskeidl commented
Fixed all merge conflicts and resolved all issues.

2023-06-23 08:07 UTC, mhellmeier approved these changes
LGTM

2023-06-23 08:07 UTC, merged